version: '3.1'
services:
 gateway:
  image: nginx
  volumes:
   - "./nginx.conf:/etc/nginx/nginx.conf"
   - "/srv/docker/nginx/htpasswd:/etc/nginx/auth.htpasswd"
   - "./letsencrypt-site:/usr/share/nginx/html"
   - "./nginx/default:/etc/nginx/sites-available/default"
   - "./nginx/default:/etc/nginx/sites-enabled/default"
   - "./public/upload:/usr/share/nginx/html"
  ports:
   - "8082:8082"
  links:
   - news-api
  depends_on:
   - news-api

 db:
  image: mysql:8.0
  ports:
   - 3306:3306
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: Root@123
   MYSQL_DATABASE: news

 news-api:
  build: .
#  ports:
#   - 8082:8082
  environment:
   DB_URL: jdbc:mysql://db:3306/news?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true&useSSL=true
   DB_PASS: Root@123
   DB_USER: root
   DB_HOST: db
  depends_on:
   - db
  expose:
   - "8082"
 adminer:
  image: adminer
  restart: always
  ports:
   - 8080:8080

